spring:
  datasource:
    url: jdbc:mysql://192.168.4.19:4401/activiti?useSSL=false
    username: root
    password: lesso2128
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  activiti:
    check-process-definitions: false